// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;



[Keyless]
public partial class AspNetUserRoles
{
    public string UserId { get; set; }
    public string RoleId { get; set; }
}