// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;




public partial class AspNetRoles
{
    public AspNetRoles()
    {
        User = new HashSet<AspNetUsers>();
    }
    [Key]
    public string Id { get; set; }
    public string Name { get; set; }
    public string NormalizedName { get; set; }
    public string ConcurrencyStamp { get; set; }

    public virtual ICollection<AspNetUsers> User { get; set; }
}