// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;



public partial class InventoryMovementDetails
{
    [Key]
    public int InventoryMovementDetailId { get; set; }
    public int MovementId { get; set; }
    public int PartId { get; set; }
    public string PartNo { get; set; }
    public int CurrentLocationId { get; set; }
    public string CurrentLocation { get; set; }
    public int DestinationLocationId { get; set; }
    public string DestinationLocation { get; set; }
    public decimal? BinQuantity { get; set; }
    public decimal? PartQuantity { get; set; }
    public DateTime? CreatedDate { get; set; }
    public int CreatedById { get; set; }
    public DateTime? LastModifiedDate { get; set; }
    public int? LastModifiedById { get; set; }
    public int? ReceivingId { get; set; }
    public int? ReceivingDetailId { get; set; }
    public int? ShippingId { get; set; }
    public int? ShippingDetailId { get; set; }
    public bool? IsNormalRequest { get; set; }
    public bool? IsReceiving { get; set; }
    public bool? IsShipping { get; set; }
    public decimal? BinQuantityBeforeMovement { get; set; }
    public decimal? PartQuantityBeforeMovement { get; set; }
    public bool? IsMoveCompleted { get; set; }
    public decimal? RemainingBinQuantity { get; set; }
    public decimal? RemainingPartQuantity { get; set; }
    public decimal? PartQuantitytoMove { get; set; }
    public decimal? BinQuantitytoMove { get; set; }
    public string SourceScanBoxBin { get; set; }
    public string DestinationScanBoxBin { get; set; }
    public bool? IsRepacking { get; set; }
    public int? RepackingOrderId { get; set; }
    public int? RepackingDetailId { get; set; }
    public DateTime? ReceivingDate { get; set; }
    public bool? IsAdditionalParts { get; set; }
    public bool? IsRepackingCreatedOnRepackingCreation { get; set; }
    public int? AdjustmentSessionId { get; set; }

    public string EmployeeName { get; set; }        //Join with Employee table to get the name
}