// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



public partial class PickingLoadTransactions
{
    [Key]
    public int PickLoadId { get; set; }
    public int TruckId { get; set; }
    public string RouteNumber { get; set; }
    public int PartId { get; set; }
    public string PartNumber { get; set; }
    public string SkidNo { get; set; }
    public decimal? PartQuantity { get; set; }
    public DateTime CreatedDate { get; set; }
    public int CreatedById { get; set; }
    public int OutBoundLocationId { get; set; }
    public bool? ShipperCreated { get; set; }
    public int? ShipperNumber { get; set; }

    //display
    //[NotMapped]
    //public string Operator { get; set; }

    public string EmployeeName { get; set; }        //Join with Employee table to get the name
    public string LocationName { get; set; }        //Join with [LocationsWithinWarehouse] table to get the name
}