// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


public partial class ReceiveOrder
{
    [Key]
    public int ReceiveOrderId { get; set; }
    public int? ReceivingId { get; set; }
    public int? ReceivingPartId { get; set; }
    public int? PartId { get; set; }
    public string PartNumber { get; set; }
    public decimal? PartQuantity { get; set; }
    public decimal? ReceivedQty { get; set; }
    public int? QtyPerBin { get; set; }
    public string TrackingInfo { get; set; }
    public int CreatedById { get; set; }

    public string EmployeeName { get; set; }        //Join with Employee table to get the name

    public DateTime? CreatedDate { get; set; }
    public int? LastModifiedById { get; set; }
    public DateTime? LastModifiedDate { get; set; }
    public bool? IsActive { get; set; }
    public string SkidsSerialno { get; set; }
}

//Display receiving Information
public class ReceivePartInfo
{
    public string PartNumber { get; set; }
    public int PartID { get; set; }
    public float PartQuantity { get; set; }
    public float PartReceived { get; set; }
    public string LocationTitle { get; set; }
    public float ReceivedQty { get; set; }
    public string SkidsSerialno { get; set; }
    public DateTime? CreatedDate { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }

    public string Operator()
    {
        return First_Name + " " + Last_Name;
    }
}