// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

public partial class ShippingLoadTransactions
{
    [Key]
    public int LoadId { get; set; }
    public int ShippingDetailId { get; set; }
    public int ShippingId { get; set; }
    public int PartId { get; set; }
    public string SkidNo { get; set; }
    public string? TrailerCode { get; set; }
    public decimal? PartQuantity { get; set; }
    public DateTime? CreatedDate { get; set; }
    public int? CreatedById { get; set; }
    public DateTime? LastModifiedDate { get; set; }
    public int? LastModifiedById { get; set; }

    public string EmployeeName { get; set; }        //Join with Employee table to get the name
    public string PartNumber { get; set; }        //Join with Parts table to get the name

}